version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    container_name: laravel_app
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
      - python
      - elasticsearch
    networks:
      - app_network

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
