version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    container_name: laravel_app
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
      - python
      - elasticsearch
    networks:
      - app_network

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql

  smtp:
    image: mailhog/mailhog
    container_name: smtp_server
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: es
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app_network
    volumes:
      - es_data:/usr/share/elasticsearch/data

  python:
    build:
      context: .
      dockerfile: docker/python.Dockerfile
    container_name: python_embeddings
    volumes:
      - ./python_service:/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
  es_data:
