name : CD - Deploy to production
on :
  push:
    branches:
      - production

jobs:
  deploy :
    runs-on: ubuntu-latest
    steps:
      - name: test ssh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "SSH connection successful"
            echo "Deploying application..."
            cd /var/www/test
            php artisan down
            git pull origin production
          run: |
            php artisan migrate --force
            php artisan optimize:clear
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan route:clear
            php artisan event:clear
            php artisan up
            echo "Deployment completed successfully"



